name: CI/CD Simples

# Quando executar
on:
  push:
    branches: [ "main" ]

# Permissão necessária para criar tags
permissions:
  contents: write

jobs:
  # NOVO JOB: Versionamento SemVer
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Essencial para pegar todas as tags
    
    - name: Gerar nova versão
      id: tag_version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
    
    - name: Criar Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: |
          📦 **Versão ${{ steps.tag_version.outputs.new_version }}**
          
          ### Mudanças:
          ${{ steps.tag_version.outputs.changelog }}
        draft: false
        prerelease: false

  teste:
    runs-on: ubuntu-latest
    needs: version 

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    # 2. Instalar Node
    - name: Instalar Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Instalar dependências
    - name: Instalar dependências
      run: npm install

    # 4. Rodar testes (opcional)
    - name: Rodar testes
      run: npm test
      continue-on-error: true

    # 5. Build (opcional)
    - name: Build
      run: echo "Build realizado com sucesso!"

    # 6. Deploy (simples simulado)
    - name: Deploy
      run: echo "Deploy realizado com sucesso 🚀"